Add support for ellipse omero rois
ajitjohnson/scimap pull request #5
Opened 2021-05-03 23:17 UTC by Yu-AnChen

2021-05-22 19:54 UTC, ajitjohnson requested changes
Hi Yuan, I am getting this error when I try to run the code

```
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/anaconda3/envs/scimap/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/opt/anaconda3/envs/scimap/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/opt/anaconda3/envs/scimap/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/envs/scimap/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/opt/anaconda3/envs/scimap/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "<stdin>", line 68, in add_roi_internal
  File "<stdin>", line 55, in get_mpatch
  File "<stdin>", line 28, in parse_roi_points
  File "/opt/anaconda3/envs/scimap/lib/python3.7/re.py", line 225, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or bytes-like object
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 75, in add_roi_omero
  File "/opt/anaconda3/envs/scimap/lib/python3.7/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/opt/anaconda3/envs/scimap/lib/python3.7/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/opt/anaconda3/envs/scimap/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/opt/anaconda3/envs/scimap/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/opt/anaconda3/envs/scimap/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
TypeError: expected string or bytes-like object
```

Below is the code that I tried

```import scimap as sm
import scanpy as sc
import pandas as pd
import numpy as np
import os



home = '/Users/aj/Dropbox (Partners HealthCare)/Data/PCA/F8 image analysis/'
adata = sc.read(str(home) + 'Z147_1_750.h5ad')

roi = pd.read_csv(str(home) + 'ROI/Z147_manuscript_roi.csv')

adata = add_roi_omero (adata, roi, label='ma2_roi')

adata.obs['ma2_roi'].value_counts()
```

Let me know I can provide you the roi file and anndata object if needed. I guess it is more of a parallel excecution error.

2021-05-25 17:53 UTC, Yu-AnChen commented
Sorry for not testing it! Just added a commit that should take care of the pandas' query rows issue, could you test it with your data again?

2021-05-25 22:46 UTC, ajitjohnson approved these changes
Thank you Yuan :)

2021-05-25 22:46 UTC, ajitjohnson approved these changes

2021-05-25 23:00 UTC, merged